name: Pull request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        run: npm install

      - name: Run tests with coverage
        run: npm run test -- --coverage --collectCoverage=true --coverageDirectory="./" --coverageReporters="lcovonly"

      - name: Restore coverage report from master branch
        uses: actions/cache@v2
        with:
          path: |
            ./base-coverage.lcov
          key: ${{ runner.os }}-master-coverage
          restore-keys: ${{ runner.os }}-master-coverage

      - name: Report code coverage
        uses: eberlitz/lcov-reporter-action@v0.2.29
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./lcov.info
          lcov-base: ./base-coverage.lcov
